fixed: configure-script could not automatically find libsigc++ on 64-bit systems

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -720,6 +720,9 @@ MV
 MKDIR
 CP
 LIBOBJS
+PKG_CONFIG
+LIBSIGC_CFLAGS
+LIBSIGC_LIBS
 ADDSRCS
 LTLIBOBJS'
 ac_subst_files=''
@@ -735,6 +738,9 @@ CCC
 CC
 CFLAGS
 CPP
+PKG_CONFIG
+LIBSIGC_CFLAGS
+LIBSIGC_LIBS
 CXXCPP'
 
 
@@ -1366,6 +1372,11 @@ Some influential environment variables:
   CC          C compiler command
   CFLAGS      C compiler flags
   CPP         C preprocessor
+  PKG_CONFIG  path to pkg-config utility
+  LIBSIGC_CFLAGS
+              C compiler flags for LIBSIGC, overriding pkg-config
+  LIBSIGC_LIBS
+              linker flags for LIBSIGC, overriding pkg-config
   CXXCPP      C++ preprocessor
 
 Use these variables to override the choices made by `configure' or to help
@@ -6899,24 +6910,262 @@ fi
 echo "${ECHO_T}$ENABLEPARCHECK" >&6; }
 if test "$ENABLEPARCHECK" = "yes"; then
 
-				INCVAL="${LIBPREF}/include/sigc++-2.0"
-	LIBVAL="${LIBPREF}/lib"
+
 
 # Check whether --with-libsigc_includes was given.
 if test "${with_libsigc_includes+set}" = set; then
-  withval=$with_libsigc_includes; INCVAL="$withval"
+  withval=$with_libsigc_includes; CPPFLAGS="${CPPFLAGS} -I${withval}"
+		INCVAL="yes"
+else
+  INCVAL="no"
 fi
 
 
 
 # Check whether --with-libsigc_libraries was given.
 if test "${with_libsigc_libraries+set}" = set; then
-  withval=$with_libsigc_libraries; LIBVAL="$withval"
+  withval=$with_libsigc_libraries; LDFLAGS="${LDFLAGS} -L${withval}"
+		CPPFLAGS="${CPPFLAGS} -I${withval}/sigc++-2.0/include"
+		LIBVAL="yes"
+else
+  LIBVAL="no"
 fi
 
 
-	LDFLAGS="${LDFLAGS} -L${LIBVAL}"
-	CPPFLAGS="${CPPFLAGS} -I${INCVAL} -I${LIBVAL}/sigc++-2.0/include"
+	if test "$INCVAL" = "no" -o "$LIBVAL" = "no"; then
+
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_ac_pt_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+if test -n "$ac_pt_PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $ac_pt_PKG_CONFIG" >&5
+echo "${ECHO_T}$ac_pt_PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+  if test "x$ac_pt_PKG_CONFIG" = x; then
+    PKG_CONFIG=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&5
+echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&2;}
+ac_tool_warned=yes ;;
+esac
+    PKG_CONFIG=$ac_pt_PKG_CONFIG
+  fi
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.9.0
+	{ echo "$as_me:$LINENO: checking pkg-config is at least version $_pkg_min_version" >&5
+echo $ECHO_N "checking pkg-config is at least version $_pkg_min_version... $ECHO_C" >&6; }
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		PKG_CONFIG=""
+	fi
+
+fi
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for LIBSIGC" >&5
+echo $ECHO_N "checking for LIBSIGC... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LIBSIGC_CFLAGS"; then
+        pkg_cv_LIBSIGC_CFLAGS="$LIBSIGC_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"sigc++-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "sigc++-2.0") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LIBSIGC_CFLAGS=`$PKG_CONFIG --cflags "sigc++-2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LIBSIGC_LIBS"; then
+        pkg_cv_LIBSIGC_LIBS="$LIBSIGC_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"sigc++-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "sigc++-2.0") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LIBSIGC_LIBS=`$PKG_CONFIG --libs "sigc++-2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LIBSIGC_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "sigc++-2.0"`
+        else
+	        LIBSIGC_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "sigc++-2.0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LIBSIGC_PKG_ERRORS" >&5
+
+	{ { echo "$as_me:$LINENO: error: Package requirements (sigc++-2.0) were not met:
+
+$LIBSIGC_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LIBSIGC_CFLAGS
+and LIBSIGC_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (sigc++-2.0) were not met:
+
+$LIBSIGC_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LIBSIGC_CFLAGS
+and LIBSIGC_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LIBSIGC_CFLAGS
+and LIBSIGC_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
+See \`config.log' for more details." >&5
+echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LIBSIGC_CFLAGS
+and LIBSIGC_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	LIBSIGC_CFLAGS=$pkg_cv_LIBSIGC_CFLAGS
+	LIBSIGC_LIBS=$pkg_cv_LIBSIGC_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	LDFLAGS="${LDFLAGS} $LIBSIGC_LIBS"
+			CPPFLAGS="${CPPFLAGS} $LIBSIGC_CFLAGS"
+fi
+	fi
 
 	ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -7284,8 +7533,8 @@ fi
 if test $ac_cv_header_sigcpp_type_traits_h = yes; then
   :
 else
-  { { echo "$as_me:$LINENO: error: \"libsigc++-2.0 header files were not found in $INCVAL.\"" >&5
-echo "$as_me: error: \"libsigc++-2.0 header files were not found in $INCVAL.\"" >&2;}
+  { { echo "$as_me:$LINENO: error: \"libsigc++-2.0 header files were not found.\"" >&5
+echo "$as_me: error: \"libsigc++-2.0 header files were not found.\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -9038,11 +9287,14 @@ MV!$MV$ac_delim
 MKDIR!$MKDIR$ac_delim
 CP!$CP$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
+PKG_CONFIG!$PKG_CONFIG$ac_delim
+LIBSIGC_CFLAGS!$LIBSIGC_CFLAGS$ac_delim
+LIBSIGC_LIBS!$LIBSIGC_LIBS$ac_delim
 ADDSRCS!$ADDSRCS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 10; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 13; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
