updated configure-script to not require gcrypt for newer GnuTLS versions (when gcrypt is not needed)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6139,50 +6139,14 @@ fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$libxml2_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (libxml-2.0) were not met:
-
-$libxml2_PKG_ERRORS
-
-Consider adjusting the PKG_CONFIG_PATH environment variable if you
-installed software in a non-standard prefix.
-
-Alternatively, you may set the environment variables libxml2_CFLAGS
-and libxml2_LIBS to avoid the need to call pkg-config.
-See the pkg-config man page for more details.
-" >&5
-echo "$as_me: error: Package requirements (libxml-2.0) were not met:
-
-$libxml2_PKG_ERRORS
-
-Consider adjusting the PKG_CONFIG_PATH environment variable if you
-installed software in a non-standard prefix.
-
-Alternatively, you may set the environment variables libxml2_CFLAGS
-and libxml2_LIBS to avoid the need to call pkg-config.
-See the pkg-config man page for more details.
-" >&2;}
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                { { echo "$as_me:$LINENO: error: \"libxml2 library not found\"" >&5
+echo "$as_me: error: \"libxml2 library not found\"" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
-	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
-is in your PATH or set the PKG_CONFIG environment variable to the full
-path to pkg-config.
-
-Alternatively, you may set the environment variables libxml2_CFLAGS
-and libxml2_LIBS to avoid the need to call pkg-config.
-See the pkg-config man page for more details.
-
-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
-See \`config.log' for more details." >&5
-echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
-is in your PATH or set the PKG_CONFIG environment variable to the full
-path to pkg-config.
-
-Alternatively, you may set the environment variables libxml2_CFLAGS
-and libxml2_LIBS to avoid the need to call pkg-config.
-See the pkg-config man page for more details.
-
-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
-See \`config.log' for more details." >&2;}
+	{ { echo "$as_me:$LINENO: error: \"libxml2 library not found\"" >&5
+echo "$as_me: error: \"libxml2 library not found\"" >&2;}
    { (exit 1); exit 1; }; }
 else
 	libxml2_CFLAGS=$pkg_cv_libxml2_CFLAGS
@@ -8847,11 +8811,9 @@ fi
 
 	{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-                FOUND=yes
-				FOUND=no
+                FOUND=no
 elif test $pkg_failed = untried; then
-	FOUND=yes
-				FOUND=no
+	FOUND=no
 else
 	openssl_CFLAGS=$pkg_cv_openssl_CFLAGS
 	openssl_LIBS=$pkg_cv_openssl_LIBS
@@ -9433,6 +9395,194 @@ echo "${ECHO_T}$ac_cv_search_gnutls_global_init" >&6; }
 ac_res=$ac_cv_search_gnutls_global_init
 if test "$ac_res" != no; then
   test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+  FOUND=yes
+else
+  FOUND=no
+fi
+
+			if test "$FOUND" = "yes"; then
+								{ echo "$as_me:$LINENO: checking whether gcrypt is needed" >&5
+echo $ECHO_N "checking whether gcrypt is needed... $ECHO_C" >&6; }
+				cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <gnutls/gnutls.h>
+					#if GNUTLS_VERSION_NUMBER <= 0x020b00
+					compile error
+					#endif
+int
+main ()
+{
+int a;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+					GCRYPT=no
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+					GCRYPT=yes
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+				if test "$GCRYPT" = "yes"; then
+					if test "${ac_cv_header_gcrypt_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for gcrypt.h" >&5
+echo $ECHO_N "checking for gcrypt.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_gcrypt_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_gcrypt_h" >&5
+echo "${ECHO_T}$ac_cv_header_gcrypt_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking gcrypt.h usability" >&5
+echo $ECHO_N "checking gcrypt.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <gcrypt.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking gcrypt.h presence" >&5
+echo $ECHO_N "checking gcrypt.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <gcrypt.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: gcrypt.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: gcrypt.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gcrypt.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: gcrypt.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: gcrypt.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: gcrypt.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gcrypt.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: gcrypt.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gcrypt.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: gcrypt.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gcrypt.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: gcrypt.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gcrypt.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: gcrypt.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: gcrypt.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: gcrypt.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------------------- ##
+## Report this to hugbug@users.sourceforge.net ##
+## ------------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for gcrypt.h" >&5
+echo $ECHO_N "checking for gcrypt.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_gcrypt_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_gcrypt_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_gcrypt_h" >&5
+echo "${ECHO_T}$ac_cv_header_gcrypt_h" >&6; }
+
+fi
+if test $ac_cv_header_gcrypt_h = yes; then
   { echo "$as_me:$LINENO: checking for library containing gcry_control" >&5
 echo $ECHO_N "checking for library containing gcry_control... $ECHO_C" >&6; }
 if test "${ac_cv_search_gcry_control+set}" = set; then
@@ -9519,9 +9669,12 @@ else
 fi
 
 else
-  FOUND=no
+  FOUND=yes
 fi
 
+
+				fi
+			fi
 			if test "$FOUND" = "no" -a "$TLSLIB" = "GnuTLS"; then
 				{ { echo "$as_me:$LINENO: error: Couldn't find GnuTLS library" >&5
 echo "$as_me: error: Couldn't find GnuTLS library" >&2;}
