added the detection of <socklen_t> type to configure script (to remove OS2-specific code from <nzbget.h>); changed configure script to avoid unneded tests when debugging is disabled

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5333,19 +5333,23 @@ fi
 fi
 
 
-{ $as_echo "$as_me:$LINENO: checking for __FUNCTION__ macro" >&5
-$as_echo_n "checking for __FUNCTION__ macro... " >&6; }
+{ $as_echo "$as_me:$LINENO: checking for type of socket length (socklen_t)" >&5
+$as_echo_n "checking for type of socket length (socklen_t)... " >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <stdio.h>
+
+#include <stddef.h>
+#include <sys/types.h>
+#include <sys/socket.h>
 int
 main ()
 {
-printf("%s\n", __FUNCTION__);
+
+(void)getsockopt (1, 1, 1, NULL, (socklen_t*)NULL)
   ;
   return 0;
 }
@@ -5368,37 +5372,30 @@ $as_echo "$ac_try_echo") >&5
 	 test -z "$ac_cxx_werror_flag" ||
 	 test ! -s conftest.err
        } && test -s conftest.$ac_objext; then
-  { $as_echo "$as_me:$LINENO: result: yes" >&5
-$as_echo "yes" >&6; }
 
-cat >>confdefs.h <<\_ACEOF
-#define FUNCTION_MACRO_NAME __FUNCTION__
-_ACEOF
-
-	HAVE_FUNCTION_MACRO=yes
+  { $as_echo "$as_me:$LINENO: result: socklen_t" >&5
+$as_echo "socklen_t" >&6; }
+  SOCKLEN_T=socklen_t
 else
   $as_echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	{ $as_echo "$as_me:$LINENO: result: no" >&5
-$as_echo "no" >&6; }
-fi
 
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-if test "$HAVE_FUNCTION_MACRO" != "yes"; then
-	{ $as_echo "$as_me:$LINENO: checking for __func__ macro" >&5
-$as_echo_n "checking for __func__ macro... " >&6; }
-	cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <stdio.h>
+
+#include <stddef.h>
+#include <sys/types.h>
+#include <sys/socket.h>
 int
 main ()
 {
-printf("%s\n", __func__);
+
+(void)getsockopt (1, 1, 1, NULL, (size_t*)NULL)
   ;
   return 0;
 }
@@ -5421,31 +5418,78 @@ $as_echo "$ac_try_echo") >&5
 	 test -z "$ac_cxx_werror_flag" ||
 	 test ! -s conftest.err
        } && test -s conftest.$ac_objext; then
-  { $as_echo "$as_me:$LINENO: result: yes" >&5
-$as_echo "yes" >&6; }
 
-cat >>confdefs.h <<\_ACEOF
-#define FUNCTION_MACRO_NAME __func__
-_ACEOF
-
-		HAVE_FUNCTION_MACRO=yes
+    { $as_echo "$as_me:$LINENO: result: size_t" >&5
+$as_echo "size_t" >&6; }
+    SOCKLEN_T=size_t
 else
   $as_echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	{ $as_echo "$as_me:$LINENO: result: no" >&5
-$as_echo "no" >&6; }
+
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <stddef.h>
+#include <sys/types.h>
+#include <sys/socket.h>
+int
+main ()
+{
+
+(void)getsockopt (1, 1, 1, NULL, (int*)NULL)
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+      { $as_echo "$as_me:$LINENO: result: int" >&5
+$as_echo "int" >&6; }
+      SOCKLEN_T=int
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+      { $as_echo "$as_me:$LINENO: WARNING: could not determine" >&5
+$as_echo "$as_me: WARNING: could not determine" >&2;}
+      SOCKLEN_T=int
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
-if test "$HAVE_FUNCTION_MACRO" != "yes"; then
 
-cat >>confdefs.h <<\_ACEOF
-#define FUNCTION_MACRO_NAME NULL
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+cat >>confdefs.h <<_ACEOF
+#define SOCKLEN_T $SOCKLEN_T
 _ACEOF
 
-fi
 
 
 
@@ -5835,8 +5879,8 @@ fi
 if test "x$ac_cv_header_libxml_tree_h" = x""yes; then
   :
 else
-  { { $as_echo "$as_me:$LINENO: error: \"libxml2 header files were not found\"" >&5
-$as_echo "$as_me: error: \"libxml2 header files were not found\"" >&2;}
+  { { $as_echo "$as_me:$LINENO: error: \"libxml2 header files not found\"" >&5
+$as_echo "$as_me: error: \"libxml2 header files not found\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -6790,8 +6834,8 @@ fi
 if test "x$ac_cv_header_sigcpp_type_traits_h" = x""yes; then
   :
 else
-  { { $as_echo "$as_me:$LINENO: error: \"libsigc++-2.0 header files were not found\"" >&5
-$as_echo "$as_me: error: \"libsigc++-2.0 header files were not found\"" >&2;}
+  { { $as_echo "$as_me:$LINENO: error: \"libsigc++-2.0 header files not found\"" >&5
+$as_echo "$as_me: error: \"libsigc++-2.0 header files not found\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -6943,8 +6987,8 @@ fi
 if test "x$ac_cv_header_libpar2_libpar2_h" = x""yes; then
   :
 else
-  { { $as_echo "$as_me:$LINENO: error: \"libpar2 header files were not found in $INCVAL\"" >&5
-$as_echo "$as_me: error: \"libpar2 header files were not found in $INCVAL\"" >&2;}
+  { { $as_echo "$as_me:$LINENO: error: \"libpar2 header files not found\"" >&5
+$as_echo "$as_me: error: \"libpar2 header files not found\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -7851,40 +7895,188 @@ else
    ENABLEDEBUG=no
 fi
 
-if test "$ENABLEDEBUG" = "yes"; then
-
-cat >>confdefs.h <<\_ACEOF
-#define DEBUG 1
-_ACEOF
-
-	if test "$CC" = "gcc"; then
-		CXXFLAGS="-g -Wall"
-	else
-		CXXFLAGS=""
-	fi
-fi
 { $as_echo "$as_me:$LINENO: result: $ENABLEDEBUG" >&5
 $as_echo "$ENABLEDEBUG" >&6; }
 
 
 if test "$ENABLEDEBUG" = "yes"; then
-	{ $as_echo "$as_me:$LINENO: checking for backtrace" >&5
-$as_echo_n "checking for backtrace... " >&6; }
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define DEBUG 1
+_ACEOF
+
+
+
+if test "$CC" = "gcc"; then
+	CXXFLAGS="-g -Wall"
+else
+	CXXFLAGS=""
+fi
+
+
+{ $as_echo "$as_me:$LINENO: checking for macro returning current function name" >&5
+$as_echo_n "checking for macro returning current function name... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdio.h>
+int
+main ()
+{
+printf("%s\n", __FUNCTION__);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  { $as_echo "$as_me:$LINENO: result: __FUNCTION__" >&5
+$as_echo "__FUNCTION__" >&6; }
+	FUNCTION_MACRO_NAME=__FUNCTION__
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
 	cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
+#include <stdio.h>
+int
+main ()
+{
+printf("%s\n", __func__);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  { $as_echo "$as_me:$LINENO: result: __func__" >&5
+$as_echo "__func__" >&6; }
+	FUNCTION_MACRO_NAME=__func__
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ $as_echo "$as_me:$LINENO: result: none" >&5
+$as_echo "none" >&6; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+if test "$FUNCTION_MACRO_NAME" != ""; then
+
+cat >>confdefs.h <<_ACEOF
+#define FUNCTION_MACRO_NAME $FUNCTION_MACRO_NAME
+_ACEOF
+
+fi
+
+
+{ $as_echo "$as_me:$LINENO: checking for variadic macros" >&5
+$as_echo_n "checking for variadic macros... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+
+	#define macro(...)   macrofunc(__VA_ARGS__)
+	int macrofunc(int a, int b) { return a + b; }
+	int test() { return macro(1, 2); }
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_VARIADIC_MACROS 1
+_ACEOF
+
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+
+{ $as_echo "$as_me:$LINENO: checking for backtrace" >&5
+$as_echo_n "checking for backtrace... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 #include <execinfo.h>
-		#include <stdio.h>
-		#include <stdlib.h>
+	#include <stdio.h>
+	#include <stdlib.h>
 int
 main ()
 {
  void *array[100];	size_t size; char **strings;
-		 size = backtrace(array, 100);
-		 strings = backtrace_symbols(array, size);
+	 size = backtrace(array, 100);
+	 strings = backtrace_symbols(array, size);
   ;
   return 0;
 }
@@ -7908,7 +8100,7 @@ $as_echo "$ac_try_echo") >&5
 	 test ! -s conftest.err
        } && test -s conftest.$ac_objext; then
   FOUND=yes
-		{ $as_echo "$as_me:$LINENO: result: yes" >&5
+	{ $as_echo "$as_me:$LINENO: result: yes" >&5
 $as_echo "yes" >&6; }
 
 cat >>confdefs.h <<\_ACEOF
@@ -7920,11 +8112,12 @@ else
 sed 's/^/| /' conftest.$ac_ext >&5
 
 	FOUND=no
-		{ $as_echo "$as_me:$LINENO: result: no" >&5
+	{ $as_echo "$as_me:$LINENO: result: no" >&5
 $as_echo "no" >&6; }
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
 
 { $as_echo "$as_me:$LINENO: checking for rdynamic linker flag" >&5
 $as_echo_n "checking for rdynamic linker flag... " >&6; }
@@ -7980,52 +8173,8 @@ fi
 rm -rf conftest.dSYM
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+
 fi
-
-
-{ $as_echo "$as_me:$LINENO: checking for variadic macros" >&5
-$as_echo_n "checking for variadic macros... " >&6; }
-cat >conftest.$ac_ext <<_ACEOF
-
-	#define macro(...)   macrofunc(__VA_ARGS__)
-	int macrofunc(int a, int b) { return a + b; }
-	int test() { return macro(1, 2); }
-
-_ACEOF
-rm -f conftest.$ac_objext
-if { (ac_try="$ac_compile"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
-$as_echo "$ac_try_echo") >&5
-  (eval "$ac_compile") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest.$ac_objext; then
-  { $as_echo "$as_me:$LINENO: result: yes" >&5
-$as_echo "yes" >&6; }
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_VARIADIC_MACROS 1
-_ACEOF
-
-else
-  $as_echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	{ $as_echo "$as_me:$LINENO: result: no" >&5
-$as_echo "no" >&6; }
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 
 
 
